const actionTypes = {
  ADD_LOGIN: 'ADD_LOGIN',
  GET_TRIVIA_QUESTIONS: 'GET_TRIVIA_QUESTIONS',
  ADD_PLAYER: 'ADD_PLAYER',
  // ADD_POINTS: 'ADD_POINTS',
  // GET_TOKEN: 'GET_TOKEN',
  // ADD_QUESTION: 'ADD_QUESTION',
};

export default actionTypes;
